repos:
  - repo: local
    hooks:
      - id: custom ruff format
        name: ruff format & sort imports
        entry: bash -c 'ruff check --select I --fix && ruff format'
        language: system
        types: [python]
        pass_filenames: false
